---
  - name: install quagga
    apt: pkg=quagga state=present update_cache=true

  - name: ensure config for each host of inventory exist
    template: src={{ item.src }} dest={{ item.dest }}
    with_items: 
      - { src: 'ospfd.conf.j2', dest: '/etc/quagga/ospfd.conf' }
      - { src: 'bgpd.conf.j2', dest: '/etc/quagga/bgpd.conf' }
      - { src: 'zebra.conf.j2', dest: '/etc/quagga/zebra.conf' }
        
  - name: copy quagga files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items: 
      - { src: 'debian.conf', dest: '/etc/quagga/debian.conf' }
      - { src: 'daemons', dest: '/etc/quagga/daemons' }

  - name: "greate dirrectory for log"
    file: 
      path: /var/log/quagga
      state: directory
      owner: quagga
      group: quagga

  - name: quagga restarted
    command: service {{ item }} restart 
    with_items:
      - ospfd
      - bgpd
      - zebra


