---
- name: Accel Install PlayBook
  hosts: local

  pre_tasks:
    - name: "read vars"
      include_vars: host_vars/{{ ansible_distribution_major_version }}.yml

  roles:
   - necessary_packages
   - linux-headers
   - accel-ppp_packages
   - accel-ppp_git
   - files
   - nat
   - modules
   - start_accel
   - firewall
   - IRQ_Affinity
  #  - web_pages
  #  - unbound