---
- name: Accel Install PlayBook
  hosts: local

  pre_tasks:
    - name: "read vars"
      include_vars: host_vars/{{ ansible_distribution_major_version }}.yml
    - name: "read kernel"
      shell: uname -r
      register: kernel
    - name: "read host"
      shell: uname -n
      register: host
    - name: Set timezone to Europe/Moscow
      command: timedatectl set-timezone Europe/Moscow


  roles:
    - necessary_packages
    - quagga
    - linux-headers
    - accel-ppp_packages
    - accel-ppp_git
    - files
    #  - nat
    - sysctl
    - modules
    - start_accel
    - firewall
    - IRQ_Affinity
    - web_pages
    - unbound
    - zabbix
    - ethtool