---
  - name: copy firewall
    template:
      src: firewall.j2
      dest: /etc/init.d/firewall
      mode: a+x

  - name: update-rc.d firewall
    command: "update-rc.d firewall defaults"

  - name: firewall started
    service:
      name: firewall
      state: started
