---

  - sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present

  - sysctl:
      name: net.ipv6.conf.all.disable_ipv6
      value: 0
      sysctl_set: yes
      state: present

  - sysctl:
      name: net.ipv6.conf.lo.disable_ipv6
      value: 0
      sysctl_set: yes
      state: present

  - sysctl:
      name: net.ipv6.conf.all.disable_ipv6
      value: 0
      sysctl_set: yes
      state: present

  - sysctl:
      name: net.ipv4.neigh.default.gc_thresh1
      value: 4096
      state: present

  - sysctl:
      name: net.ipv4.neigh.default.gc_thresh2
      value: 8192
      state: present

  - sysctl:
      name: net.ipv4.neigh.default.gc_thresh3
      value: 12288
      state: present

  - sysctl:
      name: net.ipv4.tcp_max_orphans
      value: 65536
      state: present

  - sysctl:
      name: net.ipv4.tcp_fin_timeout
      value: 30
      state: present

  - sysctl:
      name: net.ipv4.tcp_synack_retries
      value: 1
      state: present

  - sysctl:
      name: net.ipv4.tcp_mem
      value: '96552 128739 193104'
      state: present

  - sysctl:
      name: net.ipv4.tcp_rmem
      value: '4096 87380 16777216'
      state: present

  - sysctl:
      name: net.ipv4.tcp_wmem
      value: '4096 65536 16777216'
      state: present

  - sysctl:
      name: net.core.rmem_default
      value: 65536
      state: present

  - sysctl:
      name: net.core.wmem_default
      value: 65536
      state: present

  - sysctl:
      name: net.core.rmem_max
      value: 16777216
      state: present

  - sysctl:
      name: net.core.wmem_max
      value: 16777216
      state: present

  - sysctl:
      name: net.ipv4.tcp_orphan_retries
      value: 0
      state: present

  - sysctl:
      name: net.ipv4.tcp_syncookies
      value: 0
      state: present

  - sysctl:
      name: net.ipv4.tcp_no_metrics_save
      value: 1
      state: present

  - sysctl:
      name: net.ipv4.tcp_tw_reuse
      value: 1
      state: present

  - sysctl:
      name: net.ipv4.tcp_rfc1337
      value: 1
      state: present

  - sysctl:
      name: net.core.dev_weight
      value: 16
      state: present

  - sysctl:
      name: net.core.netdev_budget
      value: 512
      state: present

  - sysctl:
      name: net.core.netdev_max_backlog
      value: 30000
      state: present

  - sysctl:
      name: vm.swappiness
      value: 10
      state: present

  - sysctl:
      name: vm.dirty_background_ratio
      value: 5
      state: present

  - sysctl:
      name: vm.dirty_ratio
      value: 10
      state: present
