---

  - sysctl:
      name: net.netfilter.nf_conntrack_max
      value: 83888608
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_generic_timeout
      value: 120
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_tcp_timeout_syn_sent
      value: 30
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_tcp_timeout_syn_recv
      value: 30
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_tcp_timeout_established
      value: 300
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_tcp_timeout_fin_wait
      value: 30
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_tcp_timeout_close_wait
      value: 15
      state: present

  - sysctl: 
      name: net.netfilter.nf_conntrack_tcp_timeout_last_ack
      value: 15
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_tcp_timeout_time_wait
      value: 60
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_tcp_timeout_close
      value: 5
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_tcp_timeout_max_retrans
      value: 150
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_tcp_timeout_unacknowledged
      value: 150
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_udp_timeout
      value: 15
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_udp_timeout_stream
      value: 30
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_icmp_timeout
      value: 15
      state: present

  - sysctl:
      name: net.netfilter.nf_conntrack_checksum
      value: 0
      state: present

