---
  - name: ensure file exists
    copy:
      content: "options nf_conntrack hashsize=1193572"
      dest: /etc/modprobe.d/nf_conntrack.conf
      force: no

  - name: add nf_conntrack
    command: "modprobe nf_conntrack"

  # - name: add nf_conntrack_ipv4
  #   command: "modprobe nf_conntrack_ipv4"

  - name: nat for OS {{ ansible_distribution_major_version }}
    include: "{{ ansible_distribution_major_version }}.yml"
