---
  - name: Install necessary packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - mtr
      - atop
      - htop
      - mc
      - tcpdump
      - nload
      - ethtool
      - inetutils-traceroute

  - name: necessary packages for OS {{ ansible_distribution_major_version }}
    include: "{{ ansible_distribution_major_version }}.yml"
